languageCode: "en-us"
enableRobotsTXT: "false"
menu:
  main:
  - url: / 
    name: Home
    weight: 1
  - url: /about/
    name: About
    weight: 2
  - url: /resume/
    name: Resume
    weight: 3
  - url: /contact/
    name: Contact
    weight: 4
