languageCode: "en-us"
title: "leecalvink.net Draft"
enableRobotsTXT: "false"
menu:
  main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /about/
    weight: 20
  - name: Resume
    url: /resume/
    weight: 30
  - name: Contact
    url: /contact/
    weight: 40
