languageCode: "en-us"
enableRobotsTXT: "false"
menu:
  main:
  - name: Home
    url: /
    weight: 1
  - name: About
    url: /about/
    weight: 2
  - name: Resume
    url: /resume/
    weight: 3
  - name: Contact
    url: /contact/
    weight: 4
