baseURL: 'https://leecalvink.net/'
languageCode: 'en-us'
title: 'The Official Site for Lee Calvin Kierstead'
canonifyUrls: 'true'
disableHugoGeneratorInject: 'true'
enableRobotsTXT: 'false'
menu:
  main:
  - name: Home
    url: /
    weight: 1
  - name: About
    url: /about/
    weight: 2
  - name: Resume
    url: /resume/
    weight: 3
  - name: Contact
    url: /contact/
    weight: 4
